### ISSUE TITLE
So how do I connect all the wires

### ISSUE THREAD

**Issue by grbfst** [roberthofman/piloopdrumbox#10]
Would love to build this thing but for now have only programmed on the Pi. I have no idea how I should connect all the wires.

Also, will there be a "save" option in the future?

**Comment by m1cr0bert** [comment]
Hi, 

Thanks for your interest in this project. 
Connecting the wires indeed takes a bit of technical effort, I had a friend helping me with soldering. There may be easier options, eg with usb button pads. 

I'm not actively developing this anymore. Feel free to extend it, but I won't be implementing additional methods anymore. 

Good luck on your project!
