### ISSUE TITLE
Drumbox hardware and rpi hats

### ISSUE THREAD

**Issue by videetparekh** [roberthofman/piloopdrumbox#5]
Hey! I thought this project was super cool. I was contemplating building a midi controller with my RPi for a couple of days now but looking at this I realized quite quickly that a multichannel looper like this would be much better for my uses. 

What kind of beatpad hardware did you get, where did you get it from and did you use any RPi hats to do this? 

Edit: I watched the first bit on my phone and got super excited and forgot to watch the rest. You've already integrated a keyboard into this so you're able to accept midi inputs from other devices. Would I be able to plug a guitar into this raw and have it do the same, or would I need a ADC in between? 

Does this also support output to a DAW like Ableton?

**Comment by m1cr0bert** [comment]
For all the hardware components, take a look at the wiki!

I have a jack input, which is good enough for keyboard, but for guitar you may need a preamp.

In terms of output: you can probably build a function to save the loops, but I haven't configured that.

**Comment by videetparekh** [comment]
Would it be possible for you to share your STL/CAD file for the 3D print, do you have details about what you had to wire up and how you connected everything (like pin-2-pin descriptions)?

**Comment by m1cr0bert** [comment]
The CAD files are in the repository now. You can check the pin numbering in resources/button_pad.
