### ISSUE TITLE
LEDs not colored correctly

### ISSUE THREAD

**Issue by theghostronaut** [roberthofman/piloopdrumbox#9]
Hi,
I've set everything up using the same components as you and wired everything up according to button_pad.py.
As far as I can tell the program runs correctly, the LCD is showing the correct things and everything sounds correct.

But, the LEDs aren't lit correctly at all. When I start the program, all the LEDs turn yellow and then just start blinking. Here is a video showing what is happening:
[video](https://streamable.com/ltohrx)
I checked all the connections twice, made sure all the solder points are good but the issue persists. Do you have any idea what might be causing this? 

I am getting these errors when running the script, not sure if this is the cause?

`/home/pi/piloopdrumbox/resources/Button_pad.py:73: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(self.btnRowPins[row], GPIO.IN, pull_up_down=GPIO.PUD_UP)
/home/pi/piloopdrumbox/resources/Button_pad.py:78: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(self.colorPins[row][color], GPIO.OUT, initial=GPIO.LOW)
priority 6 scheduling failed; running at normal priority
priority 8 scheduling failed.
`

Thank you for your help!

**Comment by m1cr0bert** [comment]
Hi, 
Thanks for checking out the project! Hope i can help. Lets try to solve the priority issue, the warnings are not the problem I think.

Can you try to change the file `/etc/security/limits.conf` and add the following lines;
```
@audio - rtprio 99
@audio - memlock unlimited
```

**Comment by theghostronaut** [comment]
Hi Robert, thank your for your *very* swift response!
I added the lines and the warnings are gone now, but other than that there is no change in the behavior of the lights. I did notice after playing around a bit that the whole system seems to be kind of laggy and sometimes when I press the first button in the last row an "options" menu appears, after which everything on the lcd becomes all glitchy.

**Comment by m1cr0bert** [comment]
Yea, the last button row can be used for options, and resetting the loop. 

Maybe it's an idea to try if you can get a script running without Pd, and just checking the leds via python. Just to make sure they work and the numbering is correct.
